#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
exec python manage.py runserver_plus 0.0.0.0:8000 \
  --reloader-type stat \
  --exclude-pattern "*/media/*" \
  --exclude-pattern "*/docs/_build/*" \
  --exclude-pattern "*/.angular/*"
