# Generated by Django 4.2.9 on 2024-01-07 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("overview", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Project",
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Project Type",
            },
        ),
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("media", models.FileField(upload_to="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="project", to="projects.project"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project",
                to="projects.projecttype",
            ),
        ),
    ]
