# Generated by Django 4.2.9 on 2024-01-07 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmedia",
            options={"verbose_name_plural": "Project Medias"},
        ),
        migrations.AlterModelOptions(
            name="projecttype",
            options={"verbose_name_plural": "Project Types"},
        ),
    ]
