# Generated by Django 4.2.9 on 2024-01-18 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_options_alter_projectmedia_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmedia",
            old_name="media",
            new_name="url",
        ),
    ]
